name: Zowe Explorer (Reusable)

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJson(inputs.node-version) }}
        os: ${{ fromJson(inputs.os) }}

    timeout-minutes: 60
    concurrency:
      group: ${{ matrix.os }}-node-${{ matrix.node-version }}-ze-ci-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # install yarn
      - run: npm install -g yarn

      - run: yarn install --frozen-lockfile

      - run: yarn workspace vscode-extension-for-zowe test
        env:
          CI: true
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Upload test results
        uses: actions/upload-artifact@v1
        # if: matrix.os == 'windows-latest' && matrix.node-version == '12.x'
        with:
          name: zowe-explorer-results
          path: packages/zowe-explorer/results/

      # Run codecov upload for only one run
      - name: Upload Results to Codecov from Windows / Node 12.x
        if: matrix.os == 'windows-latest' && matrix.node-version == '12.x'
        uses: codecov/codecov-action@v1.0.7
        with:
          env_vars: OS,NODE
