name: Audit

on:
  push:
    paths:
      - packages/zowe-explorer/**
      - packages/zowe-explorer-ftp-extension/**
  pull_request:
    paths:
      - packages/zowe-explorer/**
      - packages/zowe-explorer-ftp-extension/**

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js LTS
      uses: actions/setup-node@v2
      with:
        node-version: lts/*

    - run: |
        npm install -g yarn
        yarn install --frozen-lockfile

    - name: Check Vulnerabilities
      run: yarn audit --production --groups dependencies