name: Audit

on: [push, pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest

    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, '[ci skip]')

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile

      - name: Check Vulnerabilities
        run: pnpm audit --production --groups dependencies
