name: CI

on: [push, pull_request]

jobs:
  setup:
    env:
      NODE_VERSION: '["12.x", "14.x"]'
      OS: '["windows-latest", "ubuntu-latest", "macos-latest"]'

    runs-on: ubuntu-latest
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, '[ci skip]')

    outputs:
      node-version: ${{ env.NODE_VERSION }}
      os: ${{ env.OS }}

  eslint-build:
    needs: setup
    uses: zowe/vscode-extension-for-zowe/.github/workflows/_wf-eslint-plugin-zowe-explorer.yml@test-gha-combined
    with:
      node-version: ${{ needs.setup.outputs.node-version }}
      os: ${{ needs.setup.outputs.os }}

  ze-api-build:
    needs: setup
    uses: zowe/vscode-extension-for-zowe/.github/workflows/_wf-zowe-explorer-api.yml@test-gha-combined
    with:
      node-version: ${{ needs.setup.outputs.node-version }}
      os: ${{ needs.setup.outputs.os }}

  ze-ftp-build:
    needs: setup
    uses: zowe/vscode-extension-for-zowe/.github/workflows/_wf-zowe-explorer-ftp.yml@test-gha-combined
    with:
      node-version: ${{ needs.setup.outputs.node-version }}
      os: ${{ needs.setup.outputs.os }}

  ze-build:
    needs: setup
    uses: zowe/vscode-extension-for-zowe/.github/workflows/_wf-zowe-explorer.yml@test-gha-combined
    with:
      node-version: ${{ needs.setup.outputs.node-version }}
      os: ${{ needs.setup.outputs.os }}
