name: Zowe Explorer FTP CI

on:
  push:
    paths:
      - packages/zowe-explorer-ftp-extension/**
  pull_request:
    paths:
      - packages/zowe-explorer-ftp-extension/**

jobs:
  zftp-build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Continue to run tests on the other systems if one fails
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x]
        # order operating systems from best to worst
        os: [windows-latest, ubuntu-latest, macos-latest]

    timeout-minutes: 60

    concurrency:
      group: ${{ matrix.os }}-node-${{ matrix.node-version }}-zftp-ci-${{ github.ref }}
      cancel-in-progress: true

    if: (!contains(github.event.head_commit.message, '[ci skip]'))

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # install yarn
      - run: npm install -g yarn

      - run: yarn install --frozen-lockfile

      # run audit on 1 system to avoid overloading the audit API
      - name: Audit from Windows / Node 12.x
        run: yarn workspace zowe-explorer-ftp-extension audit --production --groups dependencies
        if: matrix.os == 'windows-latest' && matrix.node-version == '12.x'

      - run: yarn workspace zowe-explorer-ftp-extension test
        env:
          CI: true
          NODE_OPTIONS: --max_old_space_size=4096
      # - name: Upload test results
      #   uses: actions/upload-artifact@v1
      #   # if: matrix.os == 'windows-latest' && matrix.node-version == '12.x'
      #   with:
      #     name: zowe-explorer-ftp-extension-results
      #     path: packages/zowe-explorer-ftp-extension/results/
      # Run codecov upload for only one run
      # - name: Upload Results to Codecov from Windows / Node 12.x
      #   if: matrix.os == 'windows-latest' && matrix.node-version == '12.x'
      #   uses: codecov/codecov-action@v1.0.7
      #   with:
      #     env_vars: OS,NODE
