name: Zowe Explorer CI

on:
  push:
    paths:
      - packages/zowe-explorer/**
  pull_request:
    paths:
      - packages/zowe-explorer/**

jobs:
  ze-build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Continue to run tests on the other systems if one fails
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # install yarn
      - run: npm install -g yarn

      - run: yarn install --frozen-lockfile

      # run audit on 1 system to avoid overloading the audit API
      - name: Audit from Windows / Node 12.x
        run: yarn audit --production --groups dependencies

      - run: yarn test
        env:
          CI: true
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Upload test results
        uses: actions/upload-artifact@v1
        with:
          name: zowe-explorer-results
          path: packages/zowe-explorer/results/

